module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '🥷', '🌸', '🪴', '💊', '☘️', '🍂', '🧚‍♀️', '👋', '😶‍🌫️', '🫀', '😉', '👀', '🪀', '🗣️', '🥰', '🗿', '💜', '🎈', '❤️‍🔥', '😩', '💀'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/HszwX4rlPogG2Mj5Qc807M?mode=wwt',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/f10i6l.jpg',
    NEWSLETTER_JID: '120363418953677198@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗡𝗔𝗥𝗨𝗧𝗢 𝗠𝗗 ',
    OWNER_NAME: 'Hirun Vikasitha',
    OWNER_NUMBER: '94702529242',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> *𝙉𝘼𝙍𝙐𝙏𝙊 - 𝙈𝘿 -  𝙈𝙄𝙉𝙄*',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbAtADv0LKZFPYOW4M2f',
};
